

services:
  
  db:
    image: postgres:14.19-trixie
    container_name: social_postgres
    environment:
      - POSTGRES_USER=piyush
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=socialnetwork
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: